language: haskell

before_install:
  - ( mkdir -p ~/.ghcup/bin && curl https://downloads.haskell.org/~ghcup/x86_64-linux-ghcup > ~/.ghcup/bin/ghcup && chmod +x ~/.ghcup/bin/ghcup) && echo "Success"
  - export PATH="$HOME/.cabal/bin:$HOME/.ghcup/bin:$PATH"
  - ghcup install 8.6.5
  - ghcup set 8.6.5
  - ghcup install-cabal 3.0.0.0

install:
  - ~/.ghcup/bin/cabal build

script:
  - ~/.ghcup/bin/cabal test
